com.sun.security.jgss.krb5.initiate {
    com.sun.security.auth.module.Krb5LoginModule required
    useKeyTab=true
    keyTab="/home/pratyush/software/eip-core-integration/eip-core-environment/demo/ibmmq/config/kerberos-jms/certs/app.keytab"
    storeKey=true
    doNotPrompt=true
    principal="app@EIP.LOCAL";
};
