security.protocol=SSL
ssl.truststore.location=/etc/kafka/secrets/audit-truststore.p12
ssl.truststore.password=password
ssl.truststore.type=PKCS12
ssl.keystore.location=/etc/kafka/secrets/client.keystore.p12
ssl.keystore.password=password
ssl.keystore.type=PKCS12
