# 01_provisioning/docker-isolated.yaml
services:
  mongodb-platform:
    image: mongo:latest
    container_name: cmongo-platform
    ports:
      - "${EIP_MONGO_PORT:-27020}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${EIP_MONGO_ROOT_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${EIP_MONGO_ROOT_PASS}"
    volumes:
      - ~/.eip/certs/mongodb/${SCENARIO}:/etc/mongodb/certs:ro
      - ~/.eip/certs/mongodb/replica.key:/etc/mongodb/replica.key:ro
    command: mongod ${EIP_MONGO_CMD_ARGS}
