services:
  mysql-platform:
    image: mysql:8.0
    container_name: mysql-platform
    environment:
      MYSQL_DATABASE: eip_db
      MYSQL_USER: eip_user
      MYSQL_PASSWORD: eip_password
      MYSQL_ROOT_PASSWORD: eip_root_password
      MYSQL_OPTS: ${MYSQL_OPTS:-}
    ports:
      - "3306:3306"
    networks:
      - eip-net

networks:
  eip-net:
