# redis-acl.conf
# Mission 3: ACL Identities (Plaintext)
# ----------------------------------------------------------------------
port 6379
user eip-user on >eip-password ~* &* +@all
protected-mode no
loglevel verbose
