
quarkus.devservices.enabled=false
quarkus.mongodb.enabled=false
quarkus.mongodb.health.enabled=false
quarkus.mongodb.connection-string=
quarkus.rest.provider=reactive
camel.component.mongodb.autowired-enabled=false

# quarkus.mongodb.connection-string=mongodb://localhost:27018
# quarkus.mongodb.eip1.connection-string=mongodb://localhost:27018
# quarkus.mongodb.eip2.connection-string=mongodb://localhost:27018

# QUARKUS_MONGODB_EIP1_CONNECTION_STRING=mongodb://localhost:27018
# QUARKUS_MONGODB_EIP2_CONNECTION_STRING=mongodb://localhost:27018
quarkus.log.category."org.mongodb.driver".level=OFF
quarkus.log.category."org.apache.camel.impl.debugger".level=ERROR

# Liquibase Configuration
quarkus.liquibase.enabled=${EIP_LIQUIBASE_ENABLED:false}
quarkus.liquibase.migrate-at-start=${EIP_LIQUIBASE_MIGRATE_AT_START:false}
quarkus.liquibase.change-log=db/changelog/db.changelog-main.yaml

