loggingLevel=info
loggingColor=true
loggingJson=false
camel.main.modeline=true
camel.jbang.compileWorkDir=.camel-jbang/compile
camel.jbang.health=false
camel.jbang.metrics=false
camel.jbang.console=false
camel.jbang.verbose=false
camel.jbang.camel-version=4.18.1
camel.jbang.springBootVersion=3.5.12
camel.jbang.quarkusVersion=3.31.3
camel.jbang.quarkusGroupId=io.quarkus.platform
camel.jbang.quarkusArtifactId=quarkus-bom
camel.jbang.kameletsVersion=4.18.0
camel.main.name=mt103-to-pacs008
camel.main.routesIncludePattern=file\:mt103-to-pacs008.yaml
dependency=mvn\:org.apache.camel\:camel-kamelet\:4.18.1
dependency=mvn\:org.apache.camel.kamelets\:camel-kamelets\:4.18.0
dependency=mvn\:org.apache.camel\:camel-yaml-dsl\:4.18.1
dependency=mvn\:org.apache.camel\:camel-file\:4.18.1
dependency=mvn\:org.apache.camel\:camel-swift\:4.18.1
dependency=mvn\:org.apache.camel\:camel-joor\:4.18.1
dependency=mvn\:org.apache.camel\:camel-xslt-saxon\:4.18.1
dependency=mvn\:org.apache.camel\:camel-core-languages\:4.18.1
