# 01_provisioning/docker-isolated.yaml
services:
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka-platform
    ports:
      - "9092:9092" # Standard PLAINTEXT
      - "9095:9095" # Standard SSL/mTLS
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:9093'
      KAFKA_LISTENERS: ${EIP_KAFKA_LISTENERS:-PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093}
      KAFKA_ADVERTISED_LISTENERS: ${EIP_KAFKA_ADVERTISED_LISTENERS:-PLAINTEXT://localhost:9092}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ${EIP_KAFKA_SEC_MAP:-CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT}
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qo'
      # Security variables will be injected via .env if active
      KAFKA_SSL_KEYSTORE_LOCATION: ${EIP_KAFKA_SSL_KEYSTORE_LOCATION:-}
      KAFKA_SSL_KEYSTORE_FILENAME: ${EIP_KAFKA_SSL_KEYSTORE_FILENAME:-}
      KAFKA_SSL_KEYSTORE_CREDENTIALS: ${EIP_KAFKA_SSL_KEYSTORE_CREDENTIALS:-}
      KAFKA_SSL_KEY_CREDENTIALS: ${EIP_KAFKA_SSL_KEY_CREDENTIALS:-}
      KAFKA_SSL_KEY_PASSWORD: ${EIP_KAFKA_SSL_KEY_PASSWORD:-}
      KAFKA_SSL_TRUSTSTORE_LOCATION: ${EIP_KAFKA_SSL_TRUSTSTORE_LOCATION:-}
      KAFKA_SSL_TRUSTSTORE_FILENAME: ${EIP_KAFKA_SSL_TRUSTSTORE_FILENAME:-}
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: ${EIP_KAFKA_SSL_TRUSTSTORE_CREDENTIALS:-}
      KAFKA_SSL_KEYSTORE_TYPE: ${EIP_KAFKA_SSL_KEYSTORE_TYPE:-JKS}
      KAFKA_SSL_TRUSTSTORE_TYPE: ${EIP_KAFKA_SSL_TRUSTSTORE_TYPE:-JKS}
      KAFKA_SSL_CLIENT_AUTH: ${EIP_KAFKA_SSL_CLIENT_AUTH:-none}
      # Single-node hardening
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - ../02_initialization/certs:/etc/kafka/secrets
